### ISSUE TITLE
makdbs example in documentation

### ISSUE THREAD

**Issue by droe-nmdp** [ogotoh/spaln#11]
In item 7 in the Format section of the README, is says 'makdbs -nxxxgnm', but I believe it should be -d, not -n: 'makdbs -dxxxgnm'.

**Comment by ogotoh** [comment]
-nxxxgnm specifies the name (prefix) of the database files. I usually omit this option, in which case xxxgnm is taken from the first argument. For example, 
makdbs -KD xxxgnm.mfa will generate xxxgnm.idx etc.

**Comment by droe-nmdp** [comment]
But there is no -n option. If you give a -n option it will name the database with the first argument. If you use -d, it will name the database given the value in the -d argument.

makdbs Version 2.0.0: format a set of sequences to be quickly addressed
Usage:
	makdbs [-d[Name]] [-sSrcdir] [-pDstdir] source_files
Option:
	-a	: Ignore abmiguity code
	-bC	: C = [e]mbl|[g]enbank|[n]brf|[p]rodb|[s]wiss
	-c	: include comments/descriptions
	-dName	: Body of file names to be created
		If omitted, default name depending on DB type
		If Name is omitted, taken from 1st source file name
	-sSrcdir	: Directory where source files are located
		If omitted, srcdir <= {., /home/roex0050/bin/spain/seqdb/, /home/roex0050/bin/spaln-Ver.2.3.2/src/../seqdb}
	-pdstdir	: Directory where destination files are located
		If omitted, dstdir = current dir
		*.ent, *.grp, *idx, (*.odr), and *.seq files are made in this directory
	-K[D|P]	: DNA or Protein sequence

**Comment by droe-nmdp** [comment]
I installed using the Ver.2.3.3 binary. The version for .../spaln-Ver.2.3.2/bin/spaln is 'SPALN version 2.3.2 <170726>', but the version of .../spaln-Ver.2.3.2/bin/makdbs is '2.0.0'.

**Comment by ogotoh** [comment]
Dear David,


Thank you for your report.

I just forgot to change a link address within the homepage (link near the bottom had been updated).

Makdbs is unchanged so as is the version number.

Osamu,

________________________________
差出人: Dave Roe <notifications@github.com>
送信日時: 2019年2月15日 2:26
宛先: ogotoh/spaln
CC: 後藤修; State change
件名: Re: [ogotoh/spaln] makdbs example in documentation (#11)


I installed using the Ver.2.3.3 binary. The version for .../spaln-Ver.2.3.2/bin/spaln is 'SPALN version 2.3.2 <170726>', but the version of .../spaln-Ver.2.3.2/bin/makdbs is '2.0.0'.
