### ISSUE TITLE
Make 2.3.3d release

### ISSUE THREAD

**Issue by nathanhaigh** [ogotoh/spaln#20]
I notice that 2.3.3d is supposed to be the latest release. However, there doesn't seem to be a release for this version. Please would you consider making a github release for the community.

**Comment by ogotoh** [comment]
I believe this Github contains the latest (2.3.3d) release. Why do you think it doesn't ?

Osamu,

**Comment by nathanhaigh** [comment]
It is not on the release page:
https://github.com/ogotoh/spaln/releases

**Comment by ogotoh** [comment]
Dear Nathan,

Thank you for your prompt response.

I just forgot to make the tag. The code itself is version 2.3.3d.

Osamu,

________________________________
差出人: Nathan S. Watson-Haigh <notifications@github.com>
送信日時: 2019年7月22日 11:01
宛先: ogotoh/spaln <spaln@noreply.github.com>
CC: 後藤修 <o.gotoh@aist.go.jp>; Comment <comment@noreply.github.com>
件名: Re: [ogotoh/spaln] Make 2.3.3d release (#20)


It is not on the release page:
https://github.com/ogotoh/spaln/releases

**Comment by nathanhaigh** [comment]
I understand. Please could you tag the repository and create the release? This is a requirement for many downstream uses to ensure reproducibility and for package managers.

**Comment by ogotoh** [comment]
I just uploaded version 2.3.3e, which fixes tiny bugs. According to your advice, the tag is attached. Thank you for your advice.

**Comment by nathanhaigh** [comment]
Awesome - thanks!
