### ISSUE TITLE
version 2.1.4 still available?

### ISSUE THREAD

**Issue by vicenciooostra** [ogotoh/spaln#25]
Hello,
I'm using an old pipeline, which relies on Spaln v2.1.4. Unfortunately I cannot find it for download (it's not on github, and the download link is dead on this site: http://www.genome.ist.i.kyoto-u.ac.jp/~aln_user/spaln/#Dwn). 

Would you still have it available? 

Kind regards,
Vicencio

**Comment by ogotoh** [comment]
The lost link to Spaln2.1.4 has been recovered at  http://www.genome.ist.i.kyoto-u.ac.jp/~aln_user/spaln/ site.

Osamu

**Comment by vicenciooostra** [comment]
Hi Osamu,

thank you for this. Any chance the binaries for Linux/x64 are also still available? I'm having trouble compiling... 

Kind regards,
V

**Comment by ogotoh** [comment]
I newly build spaln2.1.4.linux64 on CentOS 6.2. The binaries are available at the kyoto site, although no test has been done.

Osamu,

**Comment by vicenciooostra** [comment]
Hi Osamu,

thank you very much, it's working!

Kind regards,
V
