### ISSUE TITLE
Question: Is SPALN aware of soft-masked repeats?

### ISSUE THREAD

**Issue by marchoeppner** [ogotoh/spaln#31]
Hi,

I am building a genome annotation pipeline and was wondering if Spaln is at all aware of soft-masked regions in a genome sequence? This information is sometimes used (see Exonerate) to prevent the seeding of alignments in repeats, if I am not mistaken. 

Thanks for the clarification!
/M

**Comment by ogotoh** [comment]
No, Spaln isn't aware of soft-masked regions, which are treated as normal sequences. Excessively large number of k-mers are down scored to find candidate genic regions. Accordingly, repeated genomic regions are likely (but not completely) to be eliminated from candidate regions. Repeat masking is a double-edged sword. In my experience, spaln generally works better without repeat masking.

Osamu,
