### ISSUE TITLE
Compilation Spaln throws error "makdbs.h: No such file or directory"

### ISSUE THREAD

**Issue by marchoeppner** [ogotoh/spaln#33]
I, as per the other ticket, I am trying now to compile spaln from source instead of using the conda version. 

System: Centos 7, gcc 8.3

Following the instructions on git for tarball 2.4.1, I am getting this:

"makdbs.cc:24:10: fatal error: makdbs.h: No such file or directory
 #include "makdbs.h"
          ^~~~~~~~~~
compilation terminated.
make: *** [makdbs] Error 1"

I also checked the previous release 2.4.04 as well as the repository itself - this file (makdbs.h) does not seem to exist anywhere? Am I missing anything?

Cheers,
Marc

**Comment by ogotoh** [comment]
Thank you for your report.

I just forgot to add makdbs.h, which is new to this release, to the GitHub site. The missing file is now uploaded. 

There is no functional change in makdbs from 2.4.0 to 2.4.1.
