### ISSUE TITLE
Zlib non-optional

### ISSUE THREAD

**Issue by marchoeppner** [ogotoh/spaln#34]
Hi,
I have had the hardest time compiling Spaln into a Docker container, which has basically a minimal debian:latest as base system. 

When trying to set "./configure --use_zlib=0", I noticed that my build on a truly zlib-free system would fail because some part of the code still assumes Zlib to be present. Specifically "blksrc.cc" - there is a block of code that was originally written to obey the USE_ZLIB variable - but this has been uncommented:

````
#if USE_ZLIB
          , gzseq(0)
#endif
{
        entryprv[0] = '\0';
        dbname = strrealloc(0, dbn);
#if USE_ZLIB
        if (OutPrm.gzipped) {
            gzseq = gzopenpbe("", dbname, SGZ_EXT, "w", 2);
        } else
#endif
        {
            fseq = fopenpbe("", dbname, SEQ_EXT, "w", 2);
        }
        vclear(&rec);
        fidx = fopenpbe("", dbname, IDX_EXT, "w+", 2);
        fgrp = fopenpbe("", dbname, GRP_EXT, "w", 2);
        fent = fopenpbe("", dbname, ENT_EXT, "w+", 2);
}
```

**Comment by ogotoh** [comment]
I have just updated the configure script. Please try it.

Osamu,
