### ISSUE TITLE
Short sequences

### ISSUE THREAD

**Issue by RamilNurtdinov** [ogotoh/spaln#37]
Dear Osamu

I am trying to align few small RNA. I found non documented option -N that allow me to skip 
"URS000013C57A (0 - 29) 29 is too short!" like lines.

Unfortunately I got Segmentation fault
12717 Segmentation fault      (core dumped) spaln -t8 -dGRCh38 -Q4 -N17 -H5 Human_Small_RNA.fa > Mapping.txt

Is it possible to align 17 nt sequences?

Ramil

**Comment by ogotoh** [comment]
Dear Ramil,

Unfortunately, no. Spaln is designed to map relatively long transcripts, > 72 nt for DNA/RNA and 36 aa for protein. If your genome is small, it may be sensible to relax these limits by the -N option. For a mammalian-size genome, however, adjustment of MinQueryLen by the -N option would be useless or even dangerous.

Osamu,

**Comment by RamilNurtdinov** [comment]
Thank you
