### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by AlexMorscher** [ogotoh/spaln#4]
Hi,
I'm trying to install the tool. ./configure works well, but make gives me the following error:

g++ -O3 -c spaln.c
g++ -O3 -c blksrc.c
blksrc.c: In constructor ‘Randbs::Randbs(double, bool)’:
blksrc.c:1348:60: error: overloaded function with no contextual type information
 Randbs::Randbs(double avr, bool gdb) : transform(gdb? log: sqrt)
                                                                                                  ^~~~
blksrc.c:1348:60: error: overloaded function with no contextual type information
Makefile:25: recipe for target 'blksrc.o' failed
make: *** [blksrc.o] Error 1

So actually it has a problem with the 'transform(gdb? log: sqrt)' call is what I guess... How can I fix this?

Best regards,
Alex

**Comment by pvanheus** [comment]
I think this issue can be closed because the code in question has been changed in commit https://github.com/ogotoh/spaln/commit/066b85ac3866efbd911fa2359a433db6701d3f65#diff-e71a841e517bf691afc866fc5e117ebe.

**Comment by ogotoh** [comment]
Thank you for your comment. Function name 'transform' appears to collide with existing function in some systems. The function name has been changed to trans_form in an earlier release.
