### ISSUE TITLE
Spaln for mitochondrial annotation

### ISSUE THREAD

**Issue by sanyalab** [ogotoh/spaln#43]
Hello,

I wanted to know whether Spaln can be used for mitochondrial annotation using cdna and proteins. If so what parameters do you suggest would need to be given/adjusted. I am interested in plant mitochondria. The tools available for mitochondrial annotation in plants use blast, are very old, rare (just 1 that I could find) and do not output gff3 or any text files that can be easily formatted.

Please Advice.
Thanks
Abhijit

**Comment by ogotoh** [comment]
Dear Abhijit,

I haven’t thought of application of Spaln to organelle gene annotations. I am not much familiar with plant mitochondrial introns. Are they group I or group II? As the splicing boundary signals around group I introns appear to be weak, it would not be easy to precisely predict their locations with any methods. Prediction of group II introns is more hopeful. However, I need a set of positive samples to learn the parameter set used by Spaln. If you know resources of known plant mitochondrial gene annotations, please transfer me such information. I will then examine applicability of Spaln to mitochondrial gene annotation.

Best,

Osamu,

**Comment by sanyalab** [comment]
Dear Osamu,

I am new to organelle annotation as well. So some reading/research on genome structure and gene organization is needed. I have done a preliminary run with spaln on a plant mitochondrial genome, and it seems to work well, except for overlapping genes, and short introns, that I have to manually curate. 

Can we take this discussion offline? I will contact you separately after I have some data and understanding.

Best Regards,
Abhijit
