### ISSUE TITLE
cannot convert ‘gzFile’ {aka ‘gzFile_s*’} to ‘FILE*’

### ISSUE THREAD

**Issue by tillea** [ogotoh/spaln#58]
Hi,
there is a [Debian bug report](https://bugs.debian.org/1026576) that describes issues with gzFile usage:

    x86_64-linux-gnu-g++ -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -pedantic -O3 -Wall -DM_THREAD=1 -DUSE_ZLIB=1 -c gsinfo.cc 
    dbs.cc: In constructor ‘DbsDt::DbsDt(const char*)’:
    dbs.cc:568:54: error: cannot convert ‘gzFile’ {aka ‘gzFile_s*’} to ‘FILE*’
      568 |                 if (fread(dbsseq, sizeof(CHAR), rss, gzfd) <= 0)
          |                                                      ^~~~
          |                                                      |
          |                                                      gzFile {aka gzFile_s*}
    In file included from stdtype.h:25,
                     from cmn.h:25,
                     from seq.h:25,
                     from dbs.cc:22:
    /usr/include/stdio.h:676:51: note:   initializing argument 4 of ‘size_t fread(void*, size_t, size_t, FILE*)’
      676 |                      size_t __n, FILE *__restrict __stream) __wur;
          |                                  ~~~~~~~~~~~~~~~~~^~~~~~~~
    dbs.cc:570:24: error: cannot convert ‘gzFile’ {aka ‘gzFile_s*’} to ‘FILE*’
      570 |                 fclose(gzfd);
          |                        ^~~~
          |                        |
          |                        gzFile {aka gzFile_s*}
    /usr/include/stdio.h:178:26: note:   initializing argument 1 of ‘int fclose(FILE*)’
      178 | extern int fclose (FILE *__stream);
          |                    ~~~~~~^~~~~~~~
    ...

There are way more such issues so please inspect the full [bug report](https://bugs.debian.org/1026576).  Alternatively you can see a [full build log](https://salsa.debian.org/med-team/spaln/-/jobs/3688104) in our CI.

Kind regards, Andreas.

**Comment by ogotoh** [comment]
I think this bug has been fixed in ver.2.4.13d. If you still see the compilation error, please let me know.

Osamu,

**Comment by tillea** [comment]
Ahhh, sorry, the watch file we use in Debian was not working thus I missed the new versions.
