### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by kingcohn1** [ogotoh/spaln#6]
Hello, and thank you for this extremely useful program.
Fortunately, I've been able to successfully use SPALN on nearly 100 genomes, but for some reason it fails when I run it on several, consecutive genomes.
```bash 
spaln -M4 -O6 -S0 -Q7 -LS -d CPBWGS_86 LdecOR_nucleotides.fasta > ./88_1s/ors/CPBWGS_86_rm_o6_ls.8
Segmentation fault (core dumped)
```
The four genomes that fail all have the same prefix, with the number changing  CPBWGS_8[6-9]_*. Furthermore, I've curated all the genomes the same way, confirmed that all of the database files for these failed samples have been written, and the query .fasta file works for the other 90+. Hope you can provide some assistance, thank you!

**Comment by ogotoh** [comment]
From this alone, I cannot figure out what is specific to CPBWGS_8[6-9]_*. Could you upload or send me the problematic examples?
