### ISSUE TITLE
Making species specific table

### ISSUE THREAD

**Issue by jwasmuth** [ogotoh/spaln#62]
Is there a script(s) and recipe on how to make a set of parameters (AlnParam, IntronPotTab, Splice3, Splice5) for a new species? I could use the results of BUSCO (--mode genome) as known gene models. I'm aware that spaln is sensitive to the parameters used. This would help a lot. Thanks.

**Comment by ogotoh** [comment]
Sorry for the late response.

Yes, I use a script to train Spaln's parameters, given a genomic sequence and a set of cognate transcript sequences. Unfortunately, the script is somewhat messy, and it is hard to explain its usage for general users. As most parts are automated (some human intervention is still necessary to model intron-length description), I hope I can release an early version in near future.

Note that Spaln is not hyper-sensitive to the parameters, and in most cases, you may be able to substitute the taxonomically nearest existing set for the cognate one.

I have not yet examined BUSCO models.  I will try it soon. Thank you for your suggestion.

Osamu,

**Comment by jwasmuth** [comment]
Thank you Osamu. I look forward to seeing an early version
James

**Comment by ogotoh** [comment]
Dear James,

I have just uploaded new version of spaln ver3.0.0. In this version, I provide a facility to generate a species-specific parameter set. Please see makessp.md for instructions. I appreciate any your opinions on this matter.

Osamu,
