### ISSUE TITLE
What does the error "Vmf out of range" mean

### ISSUE THREAD

**Issue by sanyalab** [ogotoh/spaln#7]
Hello,

I am running uniref100 Ascomycota protein sequences against a fungal genome. I get an error "Vmf out of range". What does this mean and how to fix it. The tail end of my error file looks like below

UniRef100_A2QEX7 >     0   305 Chr_99_pilon  5047  5044  13.08   5.94 167 167 12 12 26 26
UniRef100_A2QEX8 <     0   128 Chr_8_scaffold  2321  2320   9.64   0.00  69  69  4  4  8  8
UniRef100_A2QEX9 >     0    64 Chr_13_scaffold  3674  3674   9.72   9.72  27  27  3  3  5  5
UniRef100_A2QEY2 <     0    74 Chr_13_scaffold  3637  3637   9.77   9.77  39  39  2  2  7  7
UniRef100_A2QEY5 >     0   393 Chr_11_scaffold  1237  1230   6.84   3.45 212 212 16 16 39 39
UniRef100_A2QEY6 >     0   155 Chr_14_scaffold  4122  4122  12.51  12.51  62  62  6  6 12 12
275 > 1: Vmf out of range !

Thanks
Abhijit

**Comment by ogotoh** [comment]
This error is difficult to resolve. Most likely, either genomic or query sequence has unusual features, e.g. too much errors or ambiguous residues, too short, too long, too repetitive, or others.

Please try other option of -Q and select proper parameter set with -T option.
