### ISSUE TITLE
configure script loops forever when unknown option is used

### ISSUE THREAD

**Issue by boegel** [ogotoh/spaln#74]
The `configure` script that comes with `spaln` (in the `src` directory) loops forever when an unknown option is used, for example:

```
$ cd spaln/src
$ ./configure --prefix /tmp
```

This command will never complete, since the script is stuck in the infinite while loop here:
```shell
while test $# -ge 1
do
case "$1" in
    ...
    esac
done
```

This is quite annoying, especially since there's no feedback whatsoever that an unknown option is used, and so you may be waiting minutes or even hours for the `configure` to finish whatever it's doing, before starting to try and figure out what's going on.

Most people think they know how to use a script named `configure`, since 99% of the time it's an Autotools configure script, which accepts `--prefix` as an option.

**Comment by boegel** [comment]
Other have hit this problem before, see for example #53 which mentions that the `configure` script is "stalled"

**Comment by boegel** [comment]
Proposed change to fix this: 
* #75

**Comment by ogotoh** [comment]
Dear boegel,

Thank you very much for your suggestion. I have just uploaded the revised version, Ver.3.0.6b, which includes the modified 'configure' in addition to a few minor updates in the codes.

Osamu,

**Comment by boegel** [comment]
:+1:
