### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by GenevieveKrause** [ogotoh/spaln#79]
Hello,

I am attempting to run Spaln but am getting a seg fault error. I got the error both with and without the -A1 flag. Here is the rest of the command I was running.  I am running this on a cluster via slurm and requested 16 cores. 

`spaln -t16 -M C_elegans_GCF_000002985.6_WBcel235_genomic.fna consensus_sequences.fa > spaln-C_elegans.out`

I can provide the genome and protein files if that would be helpful. 

Thank you.

**Comment by ogotoh** [comment]
Hi,

First format you genomic sequence:

$ spaln -W C_elegans -KP -t5 C_elegans_GCF_000002985.6_WBcel235_genomic.fna

Confirm that C_elegans.bkp and several  C_elegans.* files are generated. And then run

$ spaln -Q7 -d C_elegan -M -t16 consensus_sequences.fa > spaln-C_elegans.out

'C_elegans' is a tentative name; you may change it to any legitimate name you like.

Osamu,

**Comment by GenevieveKrause** [comment]
That worked.  Thank you.
