### ISSUE TITLE
Confusing output when swapping input files

### ISSUE THREAD

**Issue by pvanheus** [ogotoh/spaln#9]
Hi there - when running `spaln` in Galaxy I accidentally swapped the order of the genome and the proteins I was querying against the genome, so:

```
spaln proteins.fasta genome.fasta
```

and got the error message `No block inf !`. This is coming from `seg_job()` which in turn is called from `worker_funct()` (https://github.com/ogotoh/spaln/blob/master/src/spaln.c#L1398). In line 1401, `sbk` is set to 0 when default parameters are used and then the errant call happens because `gsquery` is true (set here https://github.com/ogotoh/spaln/blob/master/src/spaln.c#L696).

While this was clearly a user error perhaps a more useful error message could be added?

**Comment by ogotoh** [comment]
In Version.2.3.3, this issue has been fixed. The unexpected input order will be automatically exchanged with a warning message. This message can be suppressed with –pq option.
